### ISSUE TITLE
feat: add the "Hide" button that will hide the projects loaded by the "Load more"

### ISSUE THREAD

**Issue by EmmaMaltseva** [move-fast-and-break-things/mfbt.community#14]
![image](https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/92587254/63c5011c-2107-42cb-a872-5302257329a0)

The button should only be displayed if the projects were previously expanded.

**Comment by chaitanya-bhargava** [comment]
I can add this!

**Comment by yurijmikhalevich** [comment]
@chaitanya-bhargava, thank you for reaching out! Assigned this issue to you 😄 Let me know if you have any questions.

**Comment by Garrett04** [comment]
Can you assign me this?

**Comment by yurijmikhalevich** [comment]
Done in #46
