### ISSUE TITLE
feat: сделать автоматическое скрытие выпадающего меню в мобильной версии

### ISSUE THREAD

**Issue by EmmaMaltseva** [move-fast-and-break-things/mfbt.community#17]
![image](https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/92587254/9bc39d80-d12b-486b-9ffe-4a469b6a9d5d)

**Comment by yurijmikhalevich** [comment]
Unclear what's the ticket is about. Maybe, this was already fixed.
