### ISSUE TITLE
feat: fix errors reported by Google Chrome's Lighthouse to improve its score

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/mfbt.community#20]
We should get all 100's here:

<img width="973" alt="image" src="https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/4187729/40685299-4e7f-4818-a23b-8923a9d85597">

**Comment by jateez** [comment]
Hi! I'm participating in Hacktoberfest for the first time and I'd love to give this issue a try if you don't mind. Could you please assign it to me?

Thanks in advance!

**Comment by yurijmikhalevich** [comment]
Hi @jateez! Welcome to Hacktoberfest 🎉 and thank you for reaching out! Of course, assigned. Let me know if you have any questions :)
