### ISSUE TITLE
Adding a mouse follower

### ISSUE THREAD

**Issue by Speedysays01** [move-fast-and-break-things/mfbt.community#47]
A fun little mouse follower can drastically enhance the User experience. 
Please assign me this issue under Hacktoberfest2024 so I can start working on it!

**Comment by yurijmikhalevich** [comment]
@Speedysays01, thank you for the idea! I am actually not sure if we need a mouse follower 🤔 

@Misofser, what do you think?

**Comment by Speedysays01** [comment]
Thanks for considering the idea anyway! I was about to suggest something like a simple whit-ish blob following your mouse trace with a very small delay.

**Comment by yurijmikhalevich** [comment]
Closing as not needed. We decided to leave the cursor alone.
