### ISSUE TITLE
experiment: improve the UI of contributors section

### ISSUE THREAD

**Issue by Speedysays01** [move-fast-and-break-things/mfbt.community#48]
The contributors info can be enclosed in reactive cards to make it look even better.
Please assign me this issue under Hacktoberfest2024.

**Comment by Speedysays01** [comment]
I was thinking if all the contributors info would be in the forms of individual cards, it would make it look more organized. The cards can be made reactive to hover making the section more interactive.

**Comment by yurijmikhalevich** [comment]
@Speedysays01, this can be interesting. Are you open to doing this as an experiment? If we don't like it, we may not merge it 💭 

I also wan't to hear @Misofser's thoughts.

**Comment by Speedysays01** [comment]
Ya! I'm down for an experiment! Just assign the issue to me and I'll share you the screenshots first. We can modify the look to your liking and it's fine if it does not work out for you anyway.

**Comment by yurijmikhalevich** [comment]
@Speedysays01, sounds good. Thank you 🙌 

Can you please work with @Misofser on this?

**Comment by Speedysays01** [comment]
@yurijmikhalevich ON it!

**Comment by yurijmikhalevich** [comment]
Closing as unclear and stale.
