### ISSUE TITLE
feat: add the information about our mission and values

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/mfbt.community#5]
We should add the information about [the community mission and values](https://github.com/move-fast-and-break-things/mfbt.community/blob/main/CODE_OF_CONDUCT.md#code-of-conduct) to the site:

<img width="1613" alt="Screenshot 2023-10-04 at 10 03 37" src="https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/4187729/ff0eb073-f917-4bfa-ba32-e2b77b7ea133">

**Comment by AlbertJager** [comment]
This is my task :)

**Comment by 1-SubhamSingh** [comment]
So do you want to get the whole [the community mission and values] document added just above the creators section ?
If that's the case you can assign this task to me :)

**Comment by yurijmikhalevich** [comment]
@1-SubhamSingh, yes, adding a nicely formatted Mission and Values sections from the https://github.com/move-fast-and-break-things/mfbt.community/blob/main/CODE_OF_CONDUCT.md is great. Assigned to you. Thank you! 😄 

Let me or @Misofser know if you have any questions :)

**Comment by 1-SubhamSingh** [comment]
I have started working on this , I will update you within two days.

**Comment by 1-SubhamSingh** [comment]
@yurijmikhalevich  I have added the Missions and Values section, you can check and merge.
