### ISSUE TITLE
enhanced scroll bar

### ISSUE THREAD

**Issue by lord-cyclone100** [move-fast-and-break-things/mfbt.community#51]
The scrollbar can be enhanced by giving it the website color patterns.
pls assign me this task under hacktoberfest

**Comment by yurijmikhalevich** [comment]
@lord-cyclone100, great idea! Thank you for proposing it. Assigned :)

**Comment by lord-cyclone100** [comment]
@yurijmikhalevich 
Pls check my previous pr once
Thanks

**Comment by Sagarporwa1** [comment]
Hello @yurijmikhalevich  ,
I hope you're doing well! i came across issue #55 .
I’m really interested in contributing to this project, and i believe my skills in html and css make me a good fit to address this issue. i’d love to take this on and help out.
could you please assign me to this issue? if there are any specific guidelines or expectations, i'd be happy to follow them. thank you for considering my request. i look forward to contributing!
best regards,
sagar porwal
Sagarporwa

**Comment by yurijmikhalevich** [comment]
@Sagarporwa1, thank you for reaching out!

I am closing this ticket not needed. We decided to leave the scrollbar alone.
