### ISSUE TITLE
Design a footer for the page

### ISSUE THREAD

**Issue by pranavsuriya-sr** [move-fast-and-break-things/mfbt.community#53]
Creating a footer for the page makes the website look more attractive.
Example:
![image](https://github.com/user-attachments/assets/4242db37-1091-43b6-ae33-cf22920b4bf2)

**Comment by pranavsuriya-sr** [comment]
Please assign this issue to me.

**Comment by Rajgupta36** [comment]
![image](https://github.com/user-attachments/assets/231e8371-773f-4ceb-af0a-298b81927ac8)

The footer with some animation and a background video related to the community or repo looks good.

Hi @yurijmikhalevich ,
Could you please assign me this issue?

**Comment by yurijmikhalevich** [comment]
@pranavsuriya-sr, @Rajgupta36, thank you for the initiative 🙌 

We already have a nice clean footer:
<img width="1168" alt="image" src="https://github.com/user-attachments/assets/16aaca47-f256-43a7-a106-e10328f44ac1">

Before we start building a new one, let's discuss what do we want to include in it 😄 What do you have in mind?

**Comment by yurijmikhalevich** [comment]
@pranavsuriya-sr, which sections and links **exactly** do you recommend we add to the website footer?

**Comment by yurijmikhalevich** [comment]
Closing as not needed.
