### ISSUE TITLE
docs: add english translation for README.md

### ISSUE THREAD

**Issue by jateez** [move-fast-and-break-things/mfbt.community#54]
Hi,
I noticed that the current README.md is not in English. While the content is really brief and can be understood with a little bit of effort, I believe that adding an English translation could be beneficial. It would make the project more accessible to a wider, English-speaking audience and might encourage more contributions from the community.

What do you think? I'd be happy to help with the translation if you're open to the idea.

Thanks for considering!

**Comment by yurijmikhalevich** [comment]
@jateez, good catch! 🔥 Can you please translate the README into English?

**Comment by jateez** [comment]
Sure! happy to help.
