### ISSUE TITLE
fix: if project has several developers, all of them should be displayed

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/mfbt.community#6]
We should list all of the project developer names instead of saying "Community" here:

<img width="1588" alt="Screenshot 2023-10-04 at 11 00 05" src="https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/4187729/822b3ec6-a7fc-4a6b-a4e7-a7a7203abc6a">

Bonus points if we can use GitHub API for this, but we can close this PR by simply hardcoding the lists, and then follow-up with the GitHub API integration.

**Comment by LoayTarek5** [comment]
Hi @yurijmikhalevich , Hi @EmmaMaltseva , I am ready to work on this issue and I use the GitHub API to display the names of the developers. Could you please assign it to me?

**Comment by yurijmikhalevich** [comment]
@LoayTarek5, thank you for taking this issue! Assigned 😄 Let me know if you have any questions.

**Comment by LoayTarek5** [comment]
Hi @yurijmikhalevich, I hope you're doing well. I've made some changes and I'd like to know your thoughts about it and see if it's okay.
i changed every "Community" URL link and add developer names using GitHub API 

![image](https://github.com/user-attachments/assets/4911794e-3ed9-4c51-9058-d0614a438826)
![image](https://github.com/user-attachments/assets/aa966468-9715-447a-961c-47fd181f7653)
![image](https://github.com/user-attachments/assets/3a074c96-0607-4616-a67a-252838be7d40)

**Comment by LoayTarek5** [comment]
Ok @yurijmikhalevich, i will do my best

**Comment by LoayTarek5** [comment]
Is this what you want @yurijmikhalevich 
![image](https://github.com/user-attachments/assets/f33e0df6-0ff5-40be-b52b-d25ceb3a66f4)

**Comment by yurijmikhalevich** [comment]
@LoayTarek5, this is much better 🔥 Thank you 😄 

Can you submit a PR, please?

**Comment by LoayTarek5** [comment]
@yurijmikhalevich  yeah, for sure 😄
is this will count in Hacktoberfest automatically?

**Comment by yurijmikhalevich** [comment]
@LoayTarek5, it should. I'll also add the `hacktoberfest-accepted` label, to be sure 😄

**Comment by yurijmikhalevich** [comment]
Done in #56
