### ISSUE TITLE
Add hover highlight effect in the CREATORS section

### ISSUE THREAD

**Issue by anisha-singhal** [move-fast-and-break-things/mfbt.community#60]
I want to add  hover highlight effect in the CREATORS section. When we hover over someone profile it will be highlighted.

![Uploading Screenshot 2024-10-10 114203.png…]()

**Comment by yurijmikhalevich** [comment]
Hi @anisha-singhal! Thank you for reaching out. Can you reupload the screenshot, please? It looks like it failed to upload.

**Comment by anisha-singhal** [comment]
> Hi @anisha-singhal! Thank you for reaching out. Can you reupload the screenshot, please? It looks like it failed to upload.

Sure, please check
![Screenshot 2024-10-12 152528](https://github.com/user-attachments/assets/0130a3d8-2c95-4330-9ca0-c9d50e16e0e8)

**Comment by yurijmikhalevich** [comment]
@anisha-singhal, what do you mean by the hover highlight effect? Which kind of effect do you want to add?

cc @Misofser

**Comment by yurijmikhalevich** [comment]
Closing as stale.
