### ISSUE TITLE
Some formatting

### ISSUE THREAD

**Issue by Shubhamm-02** [move-fast-and-break-things/mfbt.community#62]
As we can see in some places the heading is smaller than subheadings which is making the website quite unpleasing to watch
Moreover, on clicking the community, join us, projects or creators option, we immediately get teleported to the respective section, which seems frustration, for this we can add a smooth transition which scrolls over the whole page until you reach the respective section.

**Comment by yurijmikhalevich** [comment]
@Shubhamm-02, thank you for checking out the website. I _think_ the headings being smaller than the subheadings is intentional. The point regarding the smooth scrolling can be a good idea. I'll tag @Misofser to share her thoughts.

**Comment by yurijmikhalevich** [comment]
Closing as stale and unclear.
