### ISSUE TITLE
fix: add favicon

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/mfbt.community#7]
We should add the site logo as a favicon. @Misofser can help with the design or confirm it.

<img width="1588" alt="Screenshot 2023-10-04 at 11 01 26" src="https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/4187729/05175027-645f-41e3-b2cb-81882ac66582">

**Comment by AlbertJager** [comment]
This is my task too ;)

**Comment by jobs-code** [comment]
@yurijmikhalevich @Katherine-Ya23   If this issue still pending can i work on this?

**Comment by AlbertJager** [comment]
@jobs-code Hello, John. I am already working on this task, so you can take another one.

**Comment by jobs-code** [comment]
Oh ok.

**Comment by yurijmikhalevich** [comment]
@lord-cyclone100, I am going to assign you to this ticket. Can you comment on this one, please, so I can assign it you?

**Comment by yurijmikhalevich** [comment]
Closed in favor of #44 since GitHub doesn't allow us to assign Issues until the user comments on it 😄
